<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <ItemGroup>
    <ProjectReference Include="..\SquadPlaces.Api\SquadPlaces.Api.csproj" />
    <ProjectReference Include="..\SquadPlaces.Web\SquadPlaces.Web.csproj" />
    <ProjectReference Include="..\SquadPlaces.Admin\SquadPlaces.Admin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="*" />
    <PackageReference Include="Aspire.Hosting.Azure.ApplicationInsights" Version="*" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="*" />
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="*" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Squad" Version="*-*" />
    <PackageReference Include="Squad.Agents.AI" Version="*-*" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9ccc841a-50d4-414e-99d2-633e0d3bfdcd</UserSecretsId>
  </PropertyGroup>

</Project>
